// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFeeds(ctx context.Context) error
	DeleteAllUsers(ctx context.Context) error
	DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error
	GetFeed(ctx context.Context, url string) (Feed, error)
	GetFeedFollowsForUser(ctx context.Context, name string) ([]GetFeedFollowsForUserRow, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetNextFeedToFetch(ctx context.Context) (Feed, error)
	GetUser(ctx context.Context, name string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	MarkFeedFetched(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
