// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFeeds(ctx context.Context) error
	DeleteAllUsers(ctx context.Context) error
	GetFeed(ctx context.Context, url string) (Feed, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetUser(ctx context.Context, name string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
